In [65]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color="red">04. tensorflow_v1 tensor 객체흐름</font></b>
# 1. tensorflow v2.xx 에서 v1 사용하기

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tensorflow v2 비활성화하고 v1 활성화
import numpy as np
import pandas as pd

## tensorflow
- 데이터 흐름 그래프(tensor 객체의 흐름)을 사용하는 수치 계산 라이브러리
- 그래프는 node(연산)와 edge로 구성
- sess = tf.Session()을 이용하여 실행 환경 조성
- sess.run()을 통하여 실행 결과를 확인

In [7]:
# 1단계 : tensor(상수 node 하나) 정의
node1 = tf.constant('Hello, Tensorflow')
# 2단계 : Session(연산을 실행하는 환경) 생성
sess = tf.Session()
# 3단계 : 실제 실행 및 출력
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, Tensorflow'
Hello, Tensorflow


In [9]:
# 간단한 연산 tensor 그래프
# 1. 그래프 정의
node1 = tf.constant(10, dtype=tf.float16)
node2 = tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1, node2)
# 2. Session 생성
sess = tf.Session()
# 3. Session 실행 & 결과
print(sess.run([node1, node2, node3]))

[10.0, 20.0, 30.0]


In [10]:
# 타입 변경
node1 = tf.constant(np.array([1,2,3]), dtype=tf.int16)
node2 = tf.cast(node1, dtype=tf.float32)
sess = tf.Session()
print(sess.run([node1, node2]))

[array([1, 2, 3], dtype=int16), array([1., 2., 3.], dtype=float32)]


In [12]:
# 평균값 계싼 : tf.reduce_mean()
data = np.array([1.,2.,3.,4.])
m = tf.reduce_mean(data)
sess = tf.Session()
print(sess.run(m))

2.5


In [14]:
# tf.random_normal([n]) : 평균이 0이고 표준편차가 1인 난수 n개 발생
w = tf.random_normal([3]) 
sess = tf.Session()
sess.run(w)

array([-0.6306145 ,  0.21123382, -0.35345677], dtype=float32)

In [18]:
# 변수 node
w = tf.Variable(tf.random_normal([1]))
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화
sess.run(w)

array([-1.4277825], dtype=float32)

# 2. tensorflow v1을 이용한 회귀분석 구현
## 2.1.독립변수 x가 1개, 타겟변수 y가 1개

In [20]:
# tensor 그래프 정의
# 데이터셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse)
cost = tf.reduce_mean(tf.square(H - y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차 함수이므로 곡선 그래프. 곡선 위 미분값이 0이 되는 방향으로
경사하강법 (Gradient Descent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost) 
# Session 생성
sess =tf.Session()
# W, b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b])
    if step %300==0:
        print('{}번째 cost:{}, W:{}, b:{}'.format(step, cost_val,
                                                W_val, b_val))

0번째 cost:10.524456977844238, W:[0.29847187], b:[-0.4283577]
300번째 cost:0.029939012601971626, W:[1.2004793], b:[0.5442635]
600번째 cost:0.007064411882311106, W:[1.0973842], b:[0.7786227]
900번째 cost:0.0016669194446876645, W:[1.0473051], b:[0.8924644]
1200번째 cost:0.000393326161429286, W:[1.0229788], b:[0.9477638]
1500번째 cost:9.280787344323471e-05, W:[1.011162], b:[0.9746261]
1800번째 cost:2.1899293642491102e-05, W:[1.005422], b:[0.9876744]
2100번째 cost:5.16799582328531e-06, W:[1.002634], b:[0.9940125]
2400번째 cost:1.2198141803310136e-06, W:[1.0012798], b:[0.99709105]
2700번째 cost:2.88281938765067e-07, W:[1.000622], b:[0.9985857]
3000번째 cost:6.836984312030836e-08, W:[1.0003033], b:[0.99931145]
3300번째 cost:1.6299177119094566e-08, W:[1.0001483], b:[0.9996638]
3600번째 cost:3.871011955425274e-09, W:[1.0000722], b:[0.9998361]
3900번째 cost:9.351689422842924e-10, W:[1.0000352], b:[0.99991935]
4200번째 cost:2.2019601420009138e-10, W:[1.0000173], b:[0.999961]
4500번째 cost:6.619771397708973e-11, W:[1.0000097], 

In [22]:
# 최종적으로 나온 회귀식 -> H = W * x + b
W_, b_ = sess.run([W, b])

In [23]:
W_, b_

(array([1.0000087], dtype=float32), array([0.9999811], dtype=float32))

In [28]:
def predict(x):
    return W_[0] * x + b_[0]

In [29]:
predict(5)

6.000024616718292

## 2.2.predict를 위한 placeholder 이용
- placeholder : 외부에서 데이터를 입력받을 수 있는 node

In [33]:
x = tf.placeholder(dtype=tf.float32)
H = 1 * x + 1
sess = tf.Session()
sess.run([x, H], feed_dict={x : np.array([40,50])})

[array([40., 50.], dtype=float32), array([41., 51.], dtype=float32)]

In [34]:
# tensor 그래프 정의
# 데이터셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])
# placeholder 설정(x, y)
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random_normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse)
cost = tf.reduce_mean(tf.square(H - y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차 함수이므로 곡선 그래프. 곡선 위 미분값이 0이 되는 방향으로
경사하강법 (Gradient Descent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost) 
# Session 생성
sess =tf.Session()
# W, b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b],
                                        feed_dict={x:x_data,
                                                   y:y_data})
    if step %300==0:
        print('{}번째 cost:{}, W:{}, b:{}'.format(step, cost_val,
                                                W_val, b_val))

0번째 cost:7.199756622314453, W:[0.3197032], b:[0.03861804]
300번째 cost:0.010467994958162308, W:[1.1185447], b:[0.73052]
600번째 cost:0.0024700267240405083, W:[1.057584], b:[0.8690979]
900번째 cost:0.0005828283610753715, W:[1.0279717], b:[0.9364137]
1200번째 cost:0.00013751814549323171, W:[1.0135872], b:[0.96911305]
1500번째 cost:3.244973413529806e-05, W:[1.0066003], b:[0.98499626]
1800번째 cost:7.65666027291445e-06, W:[1.0032061], b:[0.9927119]
2100번째 cost:1.8072718148687272e-06, W:[1.0015576], b:[0.9964591]
2400번째 cost:4.27084245302467e-07, W:[1.0007573], b:[0.9982788]
2700번째 cost:1.0113507187270443e-07, W:[1.0003686], b:[0.9991623]
3000번째 cost:2.4040010870862716e-08, W:[1.0001795], b:[0.9995916]
3300번째 cost:5.784784207207849e-09, W:[1.0000877], b:[0.9997998]
3600번째 cost:1.4307867113316775e-09, W:[1.0000434], b:[0.9999004]
3900번째 cost:3.3236821628257474e-10, W:[1.0000212], b:[0.99995196]
4200번째 cost:9.746751322703417e-11, W:[1.0000118], b:[0.999974]
4500번째 cost:5.195962063386794e-11, W:[1.0000086

In [35]:
# 예측하기
sess.run(H, feed_dict={x:7})

array([8.000041], dtype=float32)

## 2.3.scale이 다른 데이터들의 회귀분석 구현(scale 조정 X)

In [42]:
x_Data = np.array([1, 2, 5, 8, 10])
y_Data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost(손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# Session 생성 및 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습(scale 조정 전)
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:x_Data, y:y_Data})
    if step %300==0:
        print('{}/6000번째 cost:{}'.format(step, cost_val))

301/6000번째 cost:79.20000457763672
601/6000번째 cost:79.14115142822266
901/6000번째 cost:79.13949584960938
1201/6000번째 cost:79.13944244384766
1501/6000번째 cost:79.13944244384766
1801/6000번째 cost:79.13948059082031
2101/6000번째 cost:79.13947296142578
2401/6000번째 cost:79.13946533203125
2701/6000번째 cost:79.13946533203125
3001/6000번째 cost:79.13946533203125
3301/6000번째 cost:79.13946533203125
3601/6000번째 cost:79.13946533203125
3901/6000번째 cost:79.13946533203125
4201/6000번째 cost:79.13946533203125
4501/6000번째 cost:79.13946533203125
4801/6000번째 cost:79.13946533203125
5101/6000번째 cost:79.13946533203125
5401/6000번째 cost:79.13946533203125
5701/6000번째 cost:79.13946533203125
6001/6000번째 cost:79.13946533203125


## 2.4.scale이 다른 데이터들의 회귀분석 구현(scale 조정 O)
### scale 조정 방법 : 모든 데이터를 일정 범위 내로 조정
- normalization(정규화) : 모든 데이터를 0~1 사이로 조정
                         X - Xmin
    normalization = ─────────────────────
                       Xmax - Xmin
        
        * 위의 식보다 라이브러리 추천 (sklearn.preprocessing.MinMaxScaler)

- standardization(표준화) : 데이터의 평균을 0, 표준편차를 1로 조정
                            X - Xmean
    standardization = ─────────────────────
                           Xstd(표준편차)

        * 위의 식보다 라이브러리 추천 (sklearn.preprocessing.StandardScaler)

In [59]:
# 라이브러리 쓰지 않고 정규화
x_Data = np.array([1, 2, 5, 8, 10])
y_Data = np.array([5, 15, 68, 80, 95])
# X_data.min(), X_data.max(), X_data.mean(), X_data.std()
norm_scaled_x_Data = (x_Data - min(x_Data)) / (max(x_Data) - min(x_Data))
norm_scaled_y_Data = (y_Data - min(y_Data)) / (max(y_Data) - min(y_Data))
norm_scaled_x_Data, norm_scaled_y_Data

(array([0.        , 0.11111111, 0.44444444, 0.77777778, 1.        ]),
 array([0.        , 0.11111111, 0.7       , 0.83333333, 1.        ]))

In [58]:
# 라이브러리를 사용하여 정규화 : 라이브러리에 넣기 위해서는 n행 1열로 reshape 필요!
x_Data = x_Data.reshape(-1, 1)
y_Data = y_Data.reshape(-1, 1)
from sklearn.preprocessing import MinMaxScaler # class
scaler_x = MinMaxScaler() # 독립변수 x를 정규화시킬 객체
scaler_x.fit(x_Data)
norm_scaled_x_Data = scaler_x.transform(x_Data)
scaler_y = MinMaxScaler() # 종속변수 y를 정규화시킬 객체
norm_scaled_y_Data = scaler_y.fit_transform(y_Data)
norm_scaled_x_Data, norm_scaled_y_Data

(array([[0.        ],
        [0.11111111],
        [0.44444444],
        [0.77777778],
        [1.        ]]),
 array([[0.        ],
        [0.11111111],
        [0.7       ],
        [0.83333333],
        [1.        ]]))

In [60]:
# 라이브러리 쓰지 않고 표준화
x_Data = np.array([1, 2, 5, 8, 10])
y_Data = np.array([5, 15, 68, 80, 95])
stan_scaled_x_Data = (x_Data - x_Data.mean()) / x_Data.std()
stan_scaled_y_Data = (y_Data - y_Data.mean()) / y_Data.std()
np.column_stack([x_Data, norm_scaled_x_Data, stan_scaled_x_Data])

array([[ 1.        ,  0.        , -1.22474487],
       [ 2.        ,  0.11111111, -0.93313895],
       [ 5.        ,  0.44444444, -0.05832118],
       [ 8.        ,  0.77777778,  0.81649658],
       [10.        ,  1.        ,  1.39970842]])

In [61]:
np.column_stack([y_Data, norm_scaled_y_Data, stan_scaled_y_Data])

array([[ 5.        ,  0.        , -1.32373476],
       [15.        ,  0.11111111, -1.04563922],
       [68.        ,  0.7       ,  0.42826713],
       [80.        ,  0.83333333,  0.76198177],
       [95.        ,  1.        ,  1.17912508]])

In [62]:
# 라이브러리를 사용하여 표준화 : 라이브러리에 넣기 위해서는 n행 1열로 reshape 필요!
x_Data = x_Data.reshape(-1, 1)
y_Data = y_Data.reshape(-1, 1)
from sklearn.preprocessing import StandardScaler # class
scaler_x = StandardScaler() # 독립변수 x를 정규화시킬 객체
stan_scaled_x_Data = scaler_x.fit_transform(x_Data)
scaler_y = StandardScaler() # 종속변수 y를 정규화시킬 객체
stan_scaled_y_Data = scaler_y.fit_transform(y_Data)
stan_scaled_x_Data, stan_scaled_y_Data

(array([[-1.22474487],
        [-0.93313895],
        [-0.05832118],
        [ 0.81649658],
        [ 1.39970842]]),
 array([[-1.32373476],
        [-1.04563922],
        [ 0.42826713],
        [ 0.76198177],
        [ 1.17912508]]))

In [64]:
# 스케일 조정된 데이터를 다시 복구
scaler_y.inverse_transform(stan_scaled_y_Data)
scaler_x.inverse_transform(stan_scaled_x_Data)

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 8.],
       [10.]])

In [68]:
x_Data = np.array([1, 2, 5, 8, 10])
y_Data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost(손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# Session 생성 및 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습(scale 조정 후)
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:norm_scaled_x_Data,
                                                     y:norm_scaled_y_Data})
    if step %300==0:
        print('{}/6000번째 cost:{}'.format(step, cost_val))

300/6000번째 cost:0.2196941375732422
600/6000번째 cost:0.061570994555950165
900/6000번째 cost:0.022552696987986565
1200/6000번째 cost:0.012924492359161377
1500/6000번째 cost:0.010548633523285389
1800/6000번째 cost:0.009962363168597221
2100/6000번째 cost:0.0098176971077919
2400/6000번째 cost:0.009781996719539165
2700/6000번째 cost:0.009773186407983303
3000/6000번째 cost:0.009771013632416725
3300/6000번째 cost:0.009770478121936321
3600/6000번째 cost:0.0097703468054533
3900/6000번째 cost:0.009770313277840614
4200/6000번째 cost:0.009770303964614868
4500/6000번째 cost:0.009770301170647144
4800/6000번째 cost:0.00977030023932457
5100/6000번째 cost:0.009770301170647144
5400/6000번째 cost:0.009770302101969719
5700/6000번째 cost:0.009770302101969719
6000/6000번째 cost:0.009770302101969719
