In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

# 1. 데이터셋 가져오기

In [32]:
import numpy as np

In [3]:
import pandas as pd
df = pd.read_csv(r'C:\KI\KI\source\01_python\data\df_con(결측치 처리 후)방법1.csv')
df.head()

지역명    연도   월   평당분양가격
0  서울  2015  10  19275.3
1  서울  2015  10  18651.6
2  서울  2015  10  19410.6
3  서울  2015  10  18879.3
4  서울  2015  10  19400.7

- 지역명2 : 지역명 필드를 label encoding하여 추가
- 독립변수 : 지역명2, 연도, 월
- 타겟변수 : 평당분양가격
- 독립변수와 타겟변수의 scale 조정
    * 정규화(MinMaxScaler) 작업 후 : 지역명2n, 연도n, 월n
    * 표준화(StandardScaler) 작업 후 : 지역명2s, 연도s, 월s
   => 지역명, 연도, 월, 지역명2, 지역명2n, 연도n, 월n, 지역명2s, 연도s, 월s

# 2. 지역명의 label encoding
- 지역명2

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()
labeling_data = le.fit_transform(df['지역명'])
labeling_data

array([ 8,  8,  8, ...,  3,  2, 14])

In [6]:
df['지역명2'] = labeling_data
df['지역명2']

0         8
1         8
2         8
3         8
4         8
         ..
10909    13
10910    12
10911     3
10912     2
10913    14
Name: 지역명2, Length: 10914, dtype: int32

In [9]:
df.sample(5)

지역명    연도   월   평당분양가격  지역명2
5802  대구  2021   6  15552.9     5
4002  인천  2019   9  13087.8    11
4507  서울  2020   3  26928.0     8
5455  부산  2021   2  14163.6     7
2190  전남  2017  11   7883.7    12

# 3. MinMaxScale 조정

In [10]:
X = df[['지역명2', '연도', '월']].values # numpy 배열로 추출한 독립변수
y = df[['평당분양가격']].values
X.shape, y.shape

((10914, 3), (10914, 1))

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)
X, y

(array([[   8],
        [2015],
        [  10],
        ...,
        [  14],
        [2024],
        [   8]], dtype=int64),
 array([[19275.3],
        [18651.6],
        [19410.6],
        ...,
        [13827. ],
        [13252.8],
        [25419.9]]))

In [15]:
scaler_X = MinMaxScaler()
norm_X = scaler_X.fit_transform(X)
scaler_y = MinMaxScaler()
norm_y = scaler_y.fit_transform(y)
norm_X, norm_y

(array([[0.00395257],
        [0.99555336],
        [0.00494071],
        ...,
        [0.006917  ],
        [1.        ],
        [0.00395257]]),
 array([[0.23515833],
        [0.22397159],
        [0.23758508],
        ...,
        [0.13743711],
        [0.12713821],
        [0.34536845]]))

In [22]:
# 정규화(MinMaxScaler) 작업 후 : 지역명2n, 연도n, 월n

In [25]:
norm_X.shape, norm_y.shape

((32742, 1), (10914, 1))

In [27]:
df['지역명2n'] = norm_X[0::3].flatten()
df['연도n'] = norm_X[1::3].flatten()
df['월n'] = norm_X[2::3].flatten()
df

지역명    연도   월   평당분양가격  지역명2     지역명2n       연도n        월n
0      서울  2015  10  19275.3     8  0.003953  0.995553  0.004941
1      서울  2015  10  18651.6     8  0.003953  0.995553  0.004941
2      서울  2015  10  19410.6     8  0.003953  0.995553  0.004941
3      서울  2015  10  18879.3     8  0.003953  0.995553  0.004941
4      서울  2015  10  19400.7     8  0.003953  0.995553  0.004941
...    ..   ...  ..      ...   ...       ...       ...       ...
10909  전북  2024   8  12058.2    13  0.006423  1.000000  0.003953
10910  전남  2024   8  13120.8    12  0.005929  1.000000  0.003953
10911  경북  2024   8  13827.0     3  0.001482  1.000000  0.003953
10912  경남  2024   8  13252.8     2  0.000988  1.000000  0.003953
10913  제주  2024   8  25419.9    14  0.006917  1.000000  0.003953

[10914 rows x 8 columns]

# 4. StandardScale 조정

In [12]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler_X = StandardScaler()
stan_X = scaler_X.fit_transform(X)
scaler_y = StandardScaler()
stan_y = scaler_y.fit_transform(y)
stan_X, stan_y

(array([[-0.70629816],
        [ 1.40923707],
        [-0.70419001],
        ...,
        [-0.69997369],
        [ 1.41872377],
        [-0.70629816]]),
 array([[1.12258787],
        [1.01137862],
        [1.14671263],
        ...,
        [0.15112503],
        [0.04874191],
        [2.21820497]]))

In [23]:
# 표준화(StandardScaler) 작업 후 : 지역명2s, 연도s, 월s => 지역명, 연도, 월, 지역명2, 지역명2n, 연도n, 월n, 지역명2s, 연도s, 월s

In [28]:
df['지역명2s'] = stan_X[0::3].flatten()
df['연도s'] = stan_X[1::3].flatten()
df['월s'] = stan_X[2::3].flatten()
df

지역명    연도   월   평당분양가격  지역명2     지역명2n       연도n        월n     지역명2s  \
0      서울  2015  10  19275.3     8  0.003953  0.995553  0.004941 -0.706298   
1      서울  2015  10  18651.6     8  0.003953  0.995553  0.004941 -0.706298   
2      서울  2015  10  19410.6     8  0.003953  0.995553  0.004941 -0.706298   
3      서울  2015  10  18879.3     8  0.003953  0.995553  0.004941 -0.706298   
4      서울  2015  10  19400.7     8  0.003953  0.995553  0.004941 -0.706298   
...    ..   ...  ..      ...   ...       ...       ...       ...       ...   
10909  전북  2024   8  12058.2    13  0.006423  1.000000  0.003953 -0.701028   
10910  전남  2024   8  13120.8    12  0.005929  1.000000  0.003953 -0.702082   
10911  경북  2024   8  13827.0     3  0.001482  1.000000  0.003953 -0.711569   
10912  경남  2024   8  13252.8     2  0.000988  1.000000  0.003953 -0.712623   
10913  제주  2024   8  25419.9    14  0.006917  1.000000  0.003953 -0.699974   

            연도s        월s  
0      1.409237 -0.704190  
1      1.409237 -0.704190  
2      1.409237 -0.704190  
3      1.409237 -0.704190  
4      1.409237 -0.704190  
...         ...       ...  
10909  1.418724 -0.706298  
10910  1.418724 -0.706298  
10911  1.418724 -0.706298  
10912  1.418724 -0.706298  
10913  1.418724 -0.706298  

[10914 rows x 11 columns]

In [29]:
col = df.pop('평당분양가격') # 해당 column을 빼서 col변수에 할당
df.insert(10, '평당분양가격', col) # 10번째 열에 col 추가    

지역명    연도   월  지역명2     지역명2n       연도n        월n     지역명2s       연도s  \
0      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
1      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
2      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
3      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
4      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
...    ..   ...  ..   ...       ...       ...       ...       ...       ...   
10909  전북  2024   8    13  0.006423  1.000000  0.003953 -0.701028  1.418724   
10910  전남  2024   8    12  0.005929  1.000000  0.003953 -0.702082  1.418724   
10911  경북  2024   8     3  0.001482  1.000000  0.003953 -0.711569  1.418724   
10912  경남  2024   8     2  0.000988  1.000000  0.003953 -0.712623  1.418724   
10913  제주  2024   8    14  0.006917  1.000000  0.003953 -0.699974  1.418724   

             월s   평당분양가격  
0     -0.704190  19275.3  
1     -0.704190  18651.6  
2     -0.704190  19410.6  
3     -0.704190  18879.3  
4     -0.704190  19400.7  
...         ...      ...  
10909 -0.706298  12058.2  
10910 -0.706298  13120.8  
10911 -0.706298  13827.0  
10912 -0.706298  13252.8  
10913 -0.706298  25419.9  

[10914 rows x 11 columns]

In [31]:
df['평당분양가격n'] = norm_y
df['평당분양가격s'] = stan_y
df

지역명    연도   월  지역명2     지역명2n       연도n        월n     지역명2s       연도s  \
0      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
1      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
2      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
3      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
4      서울  2015  10     8  0.003953  0.995553  0.004941 -0.706298  1.409237   
...    ..   ...  ..   ...       ...       ...       ...       ...       ...   
10909  전북  2024   8    13  0.006423  1.000000  0.003953 -0.701028  1.418724   
10910  전남  2024   8    12  0.005929  1.000000  0.003953 -0.702082  1.418724   
10911  경북  2024   8     3  0.001482  1.000000  0.003953 -0.711569  1.418724   
10912  경남  2024   8     2  0.000988  1.000000  0.003953 -0.712623  1.418724   
10913  제주  2024   8    14  0.006917  1.000000  0.003953 -0.699974  1.418724   

             월s   평당분양가격   평당분양가격n   평당분양가격s  
0     -0.704190  19275.3  0.235158  1.122588  
1     -0.704190  18651.6  0.223972  1.011379  
2     -0.704190  19410.6  0.237585  1.146713  
3     -0.704190  18879.3  0.228056  1.051979  
4     -0.704190  19400.7  0.237408  1.144947  
...         ...      ...       ...       ...  
10909 -0.706298  12058.2  0.105712 -0.164262  
10910 -0.706298  13120.8  0.124771  0.025206  
10911 -0.706298  13827.0  0.137437  0.151125  
10912 -0.706298  13252.8  0.127138  0.048742  
10913 -0.706298  25419.9  0.345368  2.218205  

[10914 rows x 13 columns]

In [ ]:
# 스케일 조정된 데이터를 다시 복구
scaler_y.inverse_transform(stan_scaled_y_Data)
scaler_x.inverse_transform(stan_scaled_x_Data)